project_id = "qkefqkdgkbqfjuuudnir"

[functions.generate-roadmap]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.interview-assistant]
verify_jwt = false

[functions.ai-chat]
verify_jwt = true

[functions.youtube-search]
verify_jwt = false